title: TheFrontEndWorld
email: the@frontendworld.com
description: >- # this means to ignore newlines until "baseurl:"
  Describe Blog Posts
baseurl: '' # the subpath of your site, e.g. /blog
url: 'https://www.thefrontendworld.com/' # the base hostname & protocol for your site, e.g. http://example.com
instagram_username: https://www.instagram.com/front_end_world/

# Build settings
theme: minima
plugins:
  - jekyll-feed
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
